language: python
sudo: false
python:
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"
env:
 - LINT=
 - LINT=1
install:
 - npm install -g jshint
 - pip install py-mini-racer
 - pip install flake8
 - pip install wq.app
script:
 - ./runtests.sh
